# Generated by Django 3.0.6 on 2020-09-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
    ]
